/**
 * generate-plan — opt-in AcademicDecisionAgent runtime path.
 *
 * Exercises the request-level `use_academic_decision_agent` flag end-to-end
 * through the real handler (dev-bypass, no DB — same pattern as
 * generate-plan.test.ts). When the flag is absent/false the response is
 * byte-identical to before (no `academicDecision` key). When true, the handler
 * routes through the named runtime adapter (academic_decision_runtime.ts),
 * which adds an additive `academicDecision` object orchestrating clarification,
 * validation, evaluation, decision, and a Hebrew-ready explanation — while the
 * plan itself is generated by the unchanged planning path (so completed /
 * currently_taking / excluded / max_weekly_hours semantics are preserved).
 */

import handler from '../../api/ai/generate-plan';
import { randomUUID } from 'crypto';

const PLAN_CONTEXT = {
  program_name: 'בדיקה',
  semesters: [
    { id: 'year_3_semester_a', label: 'שנה ג׳ א׳', total_hours: 4, courses: [
      { course_id: 'MAND', name_he: 'חובה', hours: 4, course_type: 'mandatory', placement_policy: 'fixed', effective_allowed_semesters: ['year_3_semester_a'] },
    ] },
    { id: 'year_3_semester_b', label: 'שנה ג׳ ב׳', total_hours: 0, courses: [] },
    { id: 'year_4_semester_a', label: 'שנה ד׳ א׳', total_hours: 0, courses: [] },
    { id: 'year_4_semester_b', label: 'שנה ד׳ ב׳', total_hours: 0, courses: [] },
  ],
  category_requirements: [
    { name: 'זורמים', category_id: 'fluids', required: 1, placed: 0, candidates: [
      { course_id: 'FLU', name_he: 'זורם', hours: 4, effective_allowed_semesters: ['year_4_semester_a', 'year_4_semester_b'] },
    ] },
  ],
  total_hours_progress: { known_completed_hours: 177, degree_required_hours: 185 },
  personal_status: { completed: [] },
  mandatory_unplaced: [],
};

function makeReq(body: any, method = 'POST') {
  return { method, body } as any;
}
function makeRes() {
  const res: any = {
    statusCode: 0,
    setHeader: jest.fn().mockReturnThis(),
    status: jest.fn(function (this: any, c: number) { this.statusCode = c; return this; }),
    json: jest.fn(function (this: any, b: any) { this._body = b; return this; }),
    write: jest.fn(),
    end: jest.fn(),
  };
  return res;
}

/** Base request with sufficient inputs for the agent path: a completed course + a (possibly empty) exclusion list. */
function sufficientBody(over: any = {}) {
  return {
    program_id: 'test_program_2027',
    plan_context: {
      ...PLAN_CONTEXT,
      personal_status: { completed: [{ course_id: 'PRIOR' }], currently_taking: [] },
    },
    preferences: { disallowed_course_ids: [] },
    session_token: randomUUID(),
    ...over,
  };
}

const LEGACY_KEYS = ['blocked', 'errors', 'moves', 'rationale_he', 'requirements_status', 'semesters', 'trace', 'warnings_he'].sort();

async function run(body: any) {
  const res = makeRes();
  await handler(makeReq(body), res);
  return res;
}

describe('generate-plan — default compatibility (flag absent / false)', () => {
  beforeEach(() => {
    process.env.AI_DEV_MODE = 'true';
    process.env.AI_DEV_BYPASS_QUOTA = 'true';
  });
  afterEach(() => {
    delete process.env.AI_DEV_MODE;
    delete process.env.AI_DEV_BYPASS_QUOTA;
  });

  test('1. flag absent → no academicDecision key, exact legacy shape', async () => {
    const res = await run(sufficientBody());
    expect(res.statusCode).toBe(200);
    expect('academicDecision' in res._body).toBe(false);
    expect(Object.keys(res._body).sort()).toEqual(LEGACY_KEYS);
  });

  test('2. flag=false → no academicDecision key, exact legacy shape', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: false }));
    expect(res.statusCode).toBe(200);
    expect('academicDecision' in res._body).toBe(false);
    expect(Object.keys(res._body).sort()).toEqual(LEGACY_KEYS);
  });

  test('3. default plan fields are unchanged whether the flag is absent or false', async () => {
    const off = await run(sufficientBody());
    const falsey = await run(sufficientBody({ use_academic_decision_agent: false }));
    expect(falsey._body.semesters).toEqual(off._body.semesters);
    expect(falsey._body.moves).toEqual(off._body.moves);
    expect(falsey._body.requirements_status).toEqual(off._body.requirements_status);
  });
});

describe('generate-plan — opt-in agent path (flag=true)', () => {
  beforeEach(() => {
    process.env.AI_DEV_MODE = 'true';
    process.env.AI_DEV_BYPASS_QUOTA = 'true';
  });
  afterEach(() => {
    delete process.env.AI_DEV_MODE;
    delete process.env.AI_DEV_BYPASS_QUOTA;
  });

  test('4. flag=true routes through the runtime adapter → academicDecision present', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    expect(res.statusCode).toBe(200);
    expect(res._body.academicDecision).toBeDefined();
  });

  test('5. returns a normal plan proposal alongside academicDecision when inputs are sufficient', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    expect(Array.isArray(res._body.semesters)).toBe(true);
    expect(typeof res._body.rationale_he).toBe('string');
    expect(res._body.needsClarification).toBeFalsy();
    expect(res._body.academicDecision.decision).toBeDefined();
  });

  test('6. returns clarification instead of a plan when a critical input is missing', async () => {
    // Bare body: no completed courses, no exclusion list → critical missing.
    const res = await run({
      program_id: 'test_program_2027',
      plan_context: PLAN_CONTEXT,
      preferences: {},
      session_token: randomUUID(),
      use_academic_decision_agent: true,
    });
    expect(res.statusCode).toBe(200);
    expect(res._body.needsClarification).toBe(true);
    expect(res._body.academicDecision.clarification.needsClarification).toBe(true);
    expect(res._body.academicDecision.clarification.questions.map((q: any) => q.id)).toEqual(
      expect.arrayContaining(['completed_courses', 'excluded_courses']),
    );
    // No pretend plan.
    expect(res._body.semesters).toBeUndefined();
  });

  test('7. academicDecision includes a validation result', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    expect(res._body.academicDecision.validation).toBeDefined();
    expect(typeof res._body.academicDecision.validation.valid).toBe('boolean');
  });

  test('8. includes interestEvaluation when a meaningful academic_interest_profile is provided', async () => {
    const res = await run(sufficientBody({
      use_academic_decision_agent: true,
      academic_interest_profile: { focusAreas: [{ area: 'fluids', weight: 1 }] },
    }));
    expect(res._body.academicDecision.interestEvaluation).toBeDefined();
    expect(res._body.academicDecision.interestEvaluation.hasMeaningfulAcademicInterests).toBe(true);
  });

  test('9. does NOT include interestEvaluation when no meaningful profile exists', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    expect(res._body.academicDecision.interestEvaluation).toBeUndefined();
  });

  test('10. reports missing/needs_review topic-profile data honestly', async () => {
    // Planned MAND/FLU are not in the real ME-2027 catalog → unmatched, never fabricated.
    const res = await run(sufficientBody({
      use_academic_decision_agent: true,
      academic_interest_profile: { focusAreas: [{ area: 'fluids', weight: 1 }] },
    }));
    const ie = res._body.academicDecision.interestEvaluation;
    expect(ie.unmatchedCourseIds.length).toBeGreaterThan(0);
    expect(res._body.academicDecision.evaluation.missingDataNotes.length).toBeGreaterThan(0);
  });

  test('11. includes a decision rationale', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    expect(typeof res._body.academicDecision.decision.rationale).toBe('string');
    expect(res._body.academicDecision.decision.rationale.length).toBeGreaterThan(0);
  });

  test('12. includes a Hebrew-ready structured explanation with all five keys', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    const e = res._body.academicDecision.explanation;
    expect(typeof e.mainRecommendation).toBe('string');
    expect(Array.isArray(e.whyThisPlan)).toBe(true);
    expect(Array.isArray(e.risksAndTradeoffs)).toBe(true);
    expect(Array.isArray(e.missingData)).toBe(true);
    expect(Array.isArray(e.suggestedNextActions)).toBe(true);
  });

  test('13. includes non-empty suggested next actions', async () => {
    const res = await run(sufficientBody({ use_academic_decision_agent: true }));
    expect(res._body.academicDecision.explanation.suggestedNextActions.length).toBeGreaterThan(0);
  });
});

describe('generate-plan — agent path preserves planning semantics', () => {
  beforeEach(() => {
    process.env.AI_DEV_MODE = 'true';
    process.env.AI_DEV_BYPASS_QUOTA = 'true';
  });
  afterEach(() => {
    delete process.env.AI_DEV_MODE;
    delete process.env.AI_DEV_BYPASS_QUOTA;
  });

  function placedIds(body: any): string[] {
    return (body.semesters ?? []).flatMap((s: any) => s.course_ids);
  }

  test('14. completed_courses: the agent path produces the same plan as the default path for identical inputs', async () => {
    const base = sufficientBody();
    const off = await run({ ...base });
    const on = await run({ ...base, use_academic_decision_agent: true });
    expect(placedIds(on._body)).toEqual(placedIds(off._body));
  });

  test('15. currently_taking: a currently-taken course is not re-proposed on the agent path', async () => {
    const res = await run(sufficientBody({
      use_academic_decision_agent: true,
      plan_context: {
        ...PLAN_CONTEXT,
        personal_status: { completed: [{ course_id: 'PRIOR' }], currently_taking: [{ course_id: 'FLU' }] },
      },
    }));
    expect(placedIds(res._body)).not.toContain('FLU');
  });

  test('16. excluded_courses: a disallowed course never appears in the agent-path plan', async () => {
    const res = await run(sufficientBody({
      use_academic_decision_agent: true,
      preferences: { disallowed_course_ids: ['FLU'] },
    }));
    expect(placedIds(res._body)).not.toContain('FLU');
  });

  test('17. max_weekly_hours: the agent path honors the cap the same as the default path', async () => {
    const base = sufficientBody({ preferences: { disallowed_course_ids: [], max_weekly_hours: 8 } });
    const off = await run({ ...base });
    const on = await run({ ...base, use_academic_decision_agent: true });
    expect(placedIds(on._body)).toEqual(placedIds(off._body));
  });

  test('18. composes with the clarification-preflight resume flow when that flag is enabled', async () => {
    process.env.AI_USE_ACADEMIC_CLARIFICATION_PREFLIGHT = 'true';
    try {
      const res = await run(sufficientBody({ use_academic_decision_agent: true }));
      // Preflight is satisfied (completed present); the agent path still yields a plan + academicDecision.
      expect(res.statusCode).toBe(200);
      expect(res._body.academicDecision).toBeDefined();
      expect(Array.isArray(res._body.semesters)).toBe(true);
    } finally {
      delete process.env.AI_USE_ACADEMIC_CLARIFICATION_PREFLIGHT;
    }
  });
});
