/**
 * POST /api/ai/course-planner
 *
 * Streaming AI endpoint for TAU course-planner assistant.
 * Supports Anthropic (preferred) and OpenAI via Vercel AI SDK.
 *
 * Quota:
 *   Every request must include a session_token (UUIDv4) generated by the
 *   browser.  The server checks anonymous_sessions in Supabase and enforces
 *   a free limit (AI_FREE_QUOTA env var, default 5).  Credits are incremented
 *   only AFTER a successful response so failed AI calls are not charged.
 *
 * Runtime: Node.js (quota check requires TCP connection to Postgres).
 */

import { createAnthropic } from '@ai-sdk/anthropic';
import { createOpenAI } from '@ai-sdk/openai';
import { streamText, type LanguageModel } from 'ai';
import { z } from 'zod';
import { buildSystemPrompt, type PlanContext } from './_context';
import { checkAndEnsureSession, incrementCreditsUsed, logUsageEvent } from './_quota';

// ── Input schema ──────────────────────────────────────────────────────────────

const courseInPlanSchema = z.object({
  course_id: z.string(),
  name_he: z.string().optional(),
  hours: z.number().optional(),
  difficulty_level: z.string().optional(),
  difficulty_score: z.number().optional(),
  course_type: z.string().optional(),
  category: z.string().optional(),
  missing_prerequisites: z.array(z.string()).optional(),
});

const semesterPlanSchema = z.object({
  id: z.string(),
  label: z.string(),
  courses: z.array(courseInPlanSchema),
  total_hours: z.number(),
});

const planContextSchema = z.object({
  program_name: z.string().optional(),
  semesters: z.array(semesterPlanSchema),
  mandatory_unplaced: z
    .array(z.object({ course_id: z.string(), name_he: z.string().optional(), hours: z.number().optional() }))
    .optional(),
  requirements_progress: z
    .object({
      completed_hours: z.number(),
      required_hours: z.number(),
      categories: z.array(z.object({ name: z.string(), required: z.number(), placed: z.number() })),
    })
    .optional(),
  prerequisite_issues: z
    .array(z.object({ course_id: z.string(), name_he: z.string().optional(), missing: z.array(z.string()) }))
    .optional(),
  grade_signals: z
    .record(z.object({ average_grade: z.number().optional(), num_students_total: z.number().optional() }))
    .optional(),
});

const requestSchema = z.object({
  message:       z.string().min(1, 'message is required').max(2000, 'message too long'),
  program_id:    z.string().min(1, 'program_id is required'),
  plan_context:  planContextSchema,
  course_context: z.string().max(4000).optional(),
  session_token: z.string().uuid('session_token must be a valid UUID'),
});

// ── Model selection ───────────────────────────────────────────────────────────

interface ModelConfig { model: LanguageModel; name: string }

function resolveModel(): ModelConfig | null {
  if (process.env.ANTHROPIC_API_KEY) {
    const provider = createAnthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    return { model: provider('claude-3-5-sonnet-20241022'), name: 'claude-3-5-sonnet-20241022' };
  }
  if (process.env.OPENAI_API_KEY) {
    const provider = createOpenAI({ apiKey: process.env.OPENAI_API_KEY });
    return { model: provider('gpt-4o-mini'), name: 'gpt-4o-mini' };
  }
  return null;
}

// ── Handler (Node.js runtime) ─────────────────────────────────────────────────

export default async function handler(req: Request): Promise<Response> {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204 });
  if (req.method !== 'POST') return jsonError(405, 'Method not allowed');

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return jsonError(400, 'Invalid JSON body');
  }

  const parsed = requestSchema.safeParse(body);
  if (!parsed.success) {
    return jsonError(400, 'Invalid request', parsed.error.flatten().fieldErrors);
  }

  const { message, program_id, plan_context, course_context, session_token } = parsed.data;

  // ── AI model ─────────────────────────────────────────────────────────────
  const modelConfig = resolveModel();
  if (!modelConfig) {
    return jsonError(
      503,
      'לא הוגדר מפתח AI. בסביבת Vercel — הוסף ANTHROPIC_API_KEY בלוח הבקרה. מקומית — הגדר בקובץ .env.',
      undefined,
      'NO_API_KEY',
    );
  }

  // ── Quota check ───────────────────────────────────────────────────────────
  const dbUrl = process.env.DATABASE_URL ?? '';
  if (!dbUrl) {
    return jsonError(
      503,
      'Database not configured. Set DATABASE_URL to enable AI quota tracking.',
      undefined,
      'NO_DATABASE_URL',
    );
  }

  let quota;
  try {
    quota = await checkAndEnsureSession(session_token, dbUrl);
  } catch (err) {
    return jsonError(
      503,
      'Failed to check AI quota.',
      { detail: err instanceof Error ? err.message : String(err) },
      'DB_ERROR',
    );
  }

  if (!quota.allowed) {
    return jsonError(
      429,
      'מכסת שאלות ה-AI החינמית נוצלה.',
      {
        credits_used: quota.credits_used,
        free_limit:   quota.free_limit,
        credits_paid:  quota.credits_paid,
        remaining:     0,
      },
      'QUOTA_EXCEEDED',
    );
  }

  // ── Stream ────────────────────────────────────────────────────────────────
  const systemPrompt = buildSystemPrompt({
    program_id,
    plan_context: plan_context as PlanContext,
    course_context,
  });

  const result = streamText({
    model: modelConfig.model,
    system: systemPrompt,
    messages: [{ role: 'user', content: message }],
    maxTokens: 1024,
  });

  // Increment credits and log usage AFTER the stream completes successfully.
  // result.text resolves when all tokens have been generated.
  // If the AI generation fails, result.text rejects and the credit is not consumed.
  result.text
    .then(async () => {
      await Promise.allSettled([
        incrementCreditsUsed(session_token, dbUrl),
        logUsageEvent(session_token, modelConfig.name, dbUrl),
      ]);
    })
    .catch(() => {
      // AI generation failed — credit NOT consumed. No action needed.
    });

  return result.toTextStreamResponse({
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function jsonError(
  status: number,
  message: string,
  details?: unknown,
  code?: string,
): Response {
  const body: Record<string, unknown> = { error: message };
  if (code)    body.code    = code;
  if (details) body.details = details;
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
    },
  });
}
